alias wanip='dig +short myip.opendns.com @resolver1.opendns.com'

alias e='atom'
alias s='screen -R'

alias mosh='mosh --predict=experimental --no-init'
alias what='file -krzs'
alias mkdir='mkdir -p'

alias g='git'
alias ga='git add'
alias gc='git commit'
alias gca='git commit -a'
alias gcm='git commit -m'
alias gs='git status'
alias gd='git diff'
alias gf='git fetch'
alias gm='git merge'
alias gr='git rebase'
alias gl='git log'
alias gch='git checkout'
