#!/usr/bin/env bash
basedir=$(dirname $(readlink -f $0))
cd $basedir

exists() {
    type "$1" >/dev/null 2>&1
}

install_zsh() {
    ln -s "$basedir/zsh/.zshrc" "$HOME/.zshrc"
}

install_generic() {
    stow -t "$HOME" $1
}

for var; do
    if exists "install_$var"; then
        "install_$var"
    else
        install_generic $var
    fi
done

